export const brand = [
  {
    id: 1,
    name: "Electronics",
    image: "/image/cat/51.png",
    quantity: 150,
    sale: 120,
    status: "active",
  },
  {
    id: 2,
    name: "Books",
    image: "/image/cat/52.png",
    quantity: 200,
    sale: 75,
    status: "active",
  },
  {
    id: 3,
    name: "Clothing",
    image: "/image/cat/53.png",
    quantity: 300,
    sale: 250,
    status: "inactive",
  },
  {
    id: 4,
    name: "Home & Kitchen",
    image: "/image/cat/54.png",
    quantity: 100,
    sale: 90,
    status: "active",
  },
  {
    id: 5,
    name: "Beauty Products",
    quantity: 150,
    image: "/image/cat/55.png",
    sale: 50,
    status: "inactive",
  },
  {
    id: 6,
    name: "Toys & Games",
    image: "/image/cat/51.png",
    quantity: 80,
    sale: 60,
    status: "active",
  },
  {
    id: 7,
    name: "Automotive",
    image: "/image/cat/52.png",
    quantity: 90,
    sale: 30,
    status: "inactive",
  },
  {
    id: 8,
    name: "Health & Wellness",
    image: "/image/cat/53.png",
    quantity: 130,
    sale: 100,
    status: "active",
  },
  {
    id: 9,
    name: "Jewelry",
    image: "/image/cat/54.png",
    quantity: 70,
    sale: 40,
    status: "inactive",
  },
  {
    id: 10,
    name: "Sports Equipment",
    image: "/image/cat/55.png",
    quantity: 120,
    sale: 85,
    status: "active",
  },
  {
    id: 11,
    name: "Musical Instruments",
    image: "/image/cat/51.png",
    quantity: 55,
    sale: 20,
    status: "inactive",
  },
  {
    id: 12,
    name: "Garden Supplies",
    image: "/image/cat/52.png",
    quantity: 65,
    sale: 30,
    status: "active",
  },
  {
    id: 13,
    name: "Pet Supplies",
    image: "/image/cat/53.png",
    quantity: 110,
    sale: 90,
    status: "inactive",
  },
  {
    id: 14,
    name: "Furniture",
    image: "/image/cat/54.png",
    quantity: 45,
    sale: 25,
    status: "active",
  },
  {
    id: 15,
    name: "Office Supplies",
    quantity: 85,
    image: "/image/cat/55.png",
    sale: 50,
    status: "inactive",
  },
  {
    id: 16,
    name: "Groceries",
    image: "/image/cat/52.png",
    quantity: 300,
    sale: 260,
    status: "active",
  },
  {
    id: 17,
    name: "Footwear",
    image: "/image/cat/53.png",
    quantity: 200,
    sale: 170,
    status: "inactive",
  },
  {
    id: 18,
    name: "Bags & Accessories",
    image: "/image/cat/54.png",
    quantity: 90,
    sale: 60,
    status: "active",
  },
  {
    id: 19,
    name: "Travel Accessories",
    image: "/image/cat/55.png",
    quantity: 60,
    sale: 35,
    status: "inactive",
  },
  {
    id: 20,
    name: "Baby Products",
    image: "/image/cat/51.png",
    quantity: 130,
    sale: 110,
    status: "active",
  },
  {
    id: 21,
    name: "Stationery",
    image: "/image/cat/54.png",
    quantity: 150,
    sale: 120,
    status: "inactive",
  },
  {
    id: 22,
    name: "Art & Craft",
    image: "/image/cat/55.png",
    quantity: 100,
    sale: 80,
    status: "active",
  },
  {
    id: 23,
    name: "Mobile Accessories",
    image: "/image/cat/52.png",
    quantity: 140,
    sale: 90,
    status: "inactive",
  },
  {
    id: 24,
    name: "Video Games",
    image: "/image/cat/51.png",
    quantity: 75,
    sale: 55,
    status: "active",
  },
  {
    id: 25,
    name: "Watches",
    image: "/image/cat/53.png",
    quantity: 50,
    sale: 25,
    status: "inactive",
  },
];
